---
- name: install git
  homebrew: name=git state=latest

- name: make .zsh directory
  file: path=~/.zsh state=directory recurse=yes

- name: copy git functions
  copy: src=git.zsh dest=~/.zsh/git.zsh

- name: copy gitignore
  copy: src=gitignore dest=~/.gitignore

- name: copy gitconfig
  copy: src=gitconfig dest=~/.gitconfig
