---
- name: install languages
  homebrew: name={{item}} state=latest
  with_items:
    - cabal-install
    - elixir
    - erlang
    - go
    - groovy
    - lua
    - node
    - python
    - rust
    - scala

- name: install package managers
  homebrew: name={{item}} state=latest
  with_items:
    - gradle
    - leiningen
    - maven
    - npm

- name: tap homebrew/versions
  homebrew_tap: tap=homebrew/versions state=present

- name: install multiple rubies
  homebrew: name={{item}} state=unlinked
  with_items:
    - ruby
    - ruby193

- name: install rbenv
  homebrew: name=rbenv state=latest

- name: setup .rbenv directory
  file: path=~/.rbenv/versions state=directory recurse=yes

- name: setup .rbenv rubies
  file: src={{item.src}} dest={{item.dest}} state=link
  with_items:
    - { src: '/usr/local/Cellar/ruby/2.2.2', dest: '~/.rbenv/versions/ruby-2.2.2' }
    - { src: '/usr/local/Cellar/ruby193/1.9.3-p551_1', dest: '~/.rbenv/versions/ruby-1.9.3' }
