---
- name: install stuff
  homebrew: name={{item}} state=latest
  with_items:
    - cabal-install
    - elixir
    - erlang
    - gnu-prolog
    - go
    - gradle
    - groovy
    - io
    - lua
    - leiningen
    - maven
    - node
    - npm
    - python
    - ruby
    - rust
    - sbt
    - scala
    - typesafe-activator
  tags:
    - languages

- name: setup zsh config directory
  file: path=~/.zsh state=directory recurse=yes
  tags:
    - languages

- name: install language profile configurations
  copy: src={{item.src}} dest={{item.dest}}
  with_items:
    - { src: 'bundler.zsh', dest: '~/.zsh/bundler.zsh' }
    - { src: 'gem.zsh', dest: '~/.zsh/gem.zsh' }
    - { src: 'groovy.zsh', dest: '~/.zsh/groovy.zsh' }
    - { src: 'gemrc', dest: '~/.gemrc' }
    - { src: 'irbrc', dest: '~/.irbrc' }
  tags:
    - languages
