---
- name: setup .zsh directory
  file: path=~/.zsh state=directory recurse=yes
  tags:
    - profile

- name: install shell configurations
  copy: src={{item.src}} dest={{item.dest}}
  with_items:
    - { src: "zshrc", dest: "~/.zshrc" }
    - { src: "zshenv", dest: "~/.zshenv" }
    - { src: "bashrc", dest: "~/.bashrc" }
    - { src: "bash_profile", dest: "~/.bash_profile" }
    - { src: "misc.zsh", dest: "~/.zsh/misc.zsh" }
    - { src: "ssh.zsh", dest: "~/.zsh/ssh.zsh" }
    - { src: "mysql.zsh", dest: "~/.zsh/mysql.zsh" }
    - { src: "cqlsh.zsh", dest: "~/.zsh/cqlsh.zsh" }
    - { src: "editorconfig", dest: "~/.editorconfig" }
    - { src: "vo.zsh", dest: "~/.zsh/vo.zsh" }
    - { src: "irbrc", dest: "~/.irbrc" }
    - { src: "hushlogin", dest: "~/.hushlogin" }
    - { src: "gemrc", dest: "~/.gemrc" }
  tags:
    - profile
    - profile-configs

- name: install misc packages
  homebrew: name={{item}} state=latest
  with_items:
    - cloc
    - diff-so-fancy
    - direnv
    - dos2unix
    - editorconfig
    - hub
    - readline
    - rename
    - sl
    - tig
    - tmux
    - tree
    - wget
  tags:
    - profile

- name: tap ravenac95
  homebrew_tap: name=ravenac95/sudolikeaboss state=present
  tags:
    - profile

- name: install sudolikeaboss
  homebrew: name=sudolikeaboss state=latest
  tags:
    - profile
